### ISSUE TITLE
Certain plugins settings still appear

### ISSUE THREAD

**Issue by dianekinney** [mgibbs189/admin-cleanup#1]
Have a large site that so needs admin clean - installed, and basically "moved" anything that wasn't content to the admin menu.  Several plugins still appear as top level items in admin menu.

![image](https://cloud.githubusercontent.com/assets/3448417/14590025/67641de4-04be-11e6-826c-63f54a6fd522.png)

**Comment by mgibbs189** [comment]
@dianekinney  Thanks for reporting! Do you see any javascript errors in your browser console?

**Comment by mgibbs189** [comment]
P.S. i've just updated the code (version 0.2), which _may_ fix this issue.

**Comment by dianekinney** [comment]
The update did the trick!
